#!/usr/bin/env php
<?php
require __DIR__ . '/vendor/autoload.php';

use DI\ContainerBuilder;
use Flvrs\Statisch\App;

define('STATISCH_START', microtime(true));

$builder = new ContainerBuilder();
$builder->addDefinitions('config.php');
$container = $builder->build();

(new App($container))
    ->bootstrap([
        \Flvrs\Statisch\Commands\HelpCommand::class,
    ])
    ->run();