#!/usr/bin/env php
<?php

foreach (array(__DIR__ . '/../../autoload.php', __DIR__ . '/../vendor/autoload.php', __DIR__ . '/vendor/autoload.php') as $file) {
    if (file_exists($file)) {
        define('COMPOSER_AUTOLOADER', $file);
        break;
    }
}

unset($file);

require COMPOSER_AUTOLOADER;

use DI\ContainerBuilder;
use Flvrs\Statisch\App;

define('STATISCH_START', microtime(true));

$builder = new ContainerBuilder();
$builder->addDefinitions(__DIR__ . '/config.php');
$builder->useAutowiring(true);
$container = $builder->build();

(new App($container))
    ->bootstrap([
        \Flvrs\Statisch\Commands\HelpCommand::class,
        \Flvrs\Statisch\Commands\InstallCommand::class,
        \Flvrs\Statisch\Commands\GenerateCommand::class
    ])
    ->run();